---
- name: Install Alloy on all Alloy hosts
  hosts: alloy
  become: true
  roles:
    - role: alloy
      vars:
        alloy_version: "1.12.0"
        prometheus_server: "https://prometheus.example.com"
      